### PR TITLE
Update basic_login_box reference for CGI.pm >=4.66

### PR DESCRIPTION
**Pull request by Chris-Peterson444**
In Ubuntu, I identified a regression with cgi-application-plugin-authentication due to the latest version of CGI.pm (4.66) changing behavior with trailing slashes in URLs [1]. According to the test suite, this was the only instance of this failure I could find. I plan to apply this as a patch in Ubuntu and forward it along to Debian as well. I thought you may be interested too.

[1] https://github.com/leejo/CGI.pm/commit/a5485b5f3b2b1cc85761b6781ff6660b4f377498

### CODE REVIEW

**Comment by wesQ3** [comment]
Hi, thanks for the report and the patch.

I'd rather not change the expected output of that test as it now locks CAP::Authen to the latest CGI's. This is a legacy module in maintenance mode and I don't want to force someone rebuilding an old app to upgrade their CGI just so CAP:Authen passes tests.

I think I will shim the regression check so it accepts URLs with and without the trailing slash. Sound good?

**Comment by Chris-Peterson444** [comment]
Yeah I think that makes more sense. I should have tried to come up with something more backwards compatible in the first place, but I'm pretty unfamiliar with Perl. However, I gave it a shot this morning and updated the PR. Would something like this make more sense?

**Comment by wesQ3** [comment]
Ah we were working in parallel. I just patched the expected html if the trailing slash is present.
```
diff --git a/t/03_login_box_basic.t b/t/03_login_box_basic.t
index b0eff2f..4c14578 100644
--- a/t/03_login_box_basic.t
+++ b/t/03_login_box_basic.t
@@ -74,7 +74,13 @@ subtest 'empty' => sub {
     isa_ok($display, 'CGI::Application::Plugin::Authentication::Display');
     isa_ok($display, 'CGI::Application::Plugin::Authentication::Display::Basic');
     is($display->login_title, 'Sign In', 'title');
-    ok_regression(sub {return $display->login_box}, 't/out/basic_login_box', 'login box');
+    my $login_box_output = $display->login_box;
+    my $selfurl = $cgiapp->authen->_detaint_selfurl;
+    # shim to support CGIs >= 4.66 that return urls with trailing slashes
+    if ($selfurl eq 'http://localhost/') {
+       $login_box_output =~ s|value="$selfurl"|value="http://localhost"|;
+    }
+    ok_regression(sub { $login_box_output }, 't/out/basic_login_box', 'login box');
     is($display->logout_form, '', 'logout_form');
     is($display->is_authenticated, 0, 'is_authenticated');
     is($display->username, undef, 'username');
```
 
Thanks for spending time on this; I don't want to throw out your contribution, but I think this is a simpler approach.
I'll acknowledge you in the release commit, if that's okay?

**Comment by Chris-Peterson444** [comment]
That would be great, I appreciate it! I definitely agree your approach is best. 

I will drop the patch I applied in Ubuntu once the new version is published in Debian. Thanks!

**Pull request closed without merging**
